export const GALLERY_DATA = [
  {
    img: "/booking/booking_service_01.jpg",
    title: "Sơn Gel/Thạch",
    price: "Night Nail",
    tag: "HOT TREND",
    description:
      "Mẫu nail sơn gel/thạch mang đến vẻ ngoài trắng sữa, thanh lịch phù hợp với nhiều phong cách khác nhau.",
    features: ["Trắng sữa", "Nhũ ngọc trai", "Thanh lịch", "Nhẹ nhàng"],
    careTip:
      "Dưỡng ẩm vùng da quanh móng thường xuyên để bộ nail luôn bền đẹp.",
    nailStyle: "Ombre - Nhũ ngọc trai",
    length: "Ngắn",
    shape: "Oval",
    suitability: "Đi học, đi làm",
  },
  {
    img: "/booking/booking_service_02.jpg",
    title: "Design Mắt Mèo/Nhũ",
    price: "Night Nail",
    tag: "BASIC",
    description:
      "Mẫu nail design mắt mèo/nhũ mang đến vẻ ngoài quyến rũ, mắt mèo phù hợp với nhiều phong cách khác nhau.",
    features: ["Quyến rũ", "Huyền bí", "Mắt mèo", "Lấp lánh"],
    careTip: "Hạn chế tiếp xúc trực tiếp với hóa chất tẩy rửa mạnh.",
    nailStyle: "Sơn thạch trong veo",
    length: "Vừa",
    shape: "Vuông",
    suitability: "Dự tiệc, sự kiện",
  },
  {
    img: "/booking/booking_service_03.jpg",
    title: "Sơn Gel/Thạch",
    price: "Night Nail",
    tag: "BEST SELLER",
    description:
      "Mẫu nail sơn gel/thạch mang đến vẻ ngoài tôn da, tinh tế phù hợp với nhiều phong cách khác nhau.",
    features: ["Tôn da", "Đơn giản", "Tinh tế", "Thạch"],
    careTip: "Sử dụng găng tay khi làm việc nhà để bảo vệ màu sơn.",
    nailStyle: "Mắt mèo kim cương",
    length: "Dài",
    shape: "Nhọn",
    suitability: "Hẹn hò, dạo phố",
  },
  {
    img: "/booking/booking_service_04.jpg",
    title: "Design Cơ Bản",
    price: "Night Nail",
    tag: "NEW",
    description:
      "Mẫu nail design cơ bản mang đến vẻ ngoài sang trọng, nổi bật phù hợp với nhiều phong cách khác nhau.",
    features: ["Sang trọng", "Đính đá", "Nổi bật", "Tiệc tùng"],
    careTip: "Tránh dùng móng cạy các vật cứng để không làm mẻ gel.",
    nailStyle: "Tráng gương sang trọng",
    length: "Cực dài",
    shape: "Thang",
    suitability: "Cô dâu trong ngày cưới",
  },
  {
    img: "/booking/booking_service_05.jpg",
    title: "Design Full Dặm Đầu Móng",
    price: "Night Nail",
    tag: "HOT TREND",
    description:
      "Mẫu nail design full dặm đầu móng mang đến vẻ ngoài cá tính, độc đáo phù hợp với nhiều phong cách khác nhau.",
    features: ["Cá tính", "Tráng gương", "Độc đáo", "Hiện đại"],
    careTip: "Thoa dầu dưỡng móng mỗi tối trước khi đi ngủ.",
    nailStyle: "Đính đá lấp lánh",
    length: "Ngắn",
    shape: "Hạnh nhân",
    suitability: "Đi học, đi làm",
  },
  {
    img: "/images/process/26.png",
    title: "Premium Design",
    price: "Night Nail",
    tag: "BEST SELLER",
    description:
      "Mẫu nail premium design mang đến vẻ ngoài trắng sữa, thanh lịch phù hợp với nhiều phong cách khác nhau.",
    features: ["Trắng sữa", "Nhũ ngọc trai", "Thanh lịch", "Nhẹ nhàng"],
    careTip:
      "Dưỡng ẩm vùng da quanh móng thường xuyên để bộ nail luôn bền đẹp.",
    nailStyle: "Vẽ vân đá hoa cương",
    length: "Vừa",
    shape: "Oval",
    suitability: "Dự tiệc, sự kiện",
  },
  {
    img: "/images/process/27.png",
    title: "Premium Design",
    price: "Night Nail",
    tag: "NEW",
    description:
      "Mẫu nail premium design mang đến vẻ ngoài quyến rũ, mắt mèo phù hợp với nhiều phong cách khác nhau.",
    features: ["Quyến rũ", "Huyền bí", "Mắt mèo", "Lấp lánh"],
    careTip: "Hạn chế tiếp xúc trực tiếp với hóa chất tẩy rửa mạnh.",
    nailStyle: "Ombre - Nhũ ngọc trai",
    length: "Dài",
    shape: "Vuông",
    suitability: "Hẹn hò, dạo phố",
  },
  {
    img: "/images/process/28.png",
    title: "Premium Design",
    price: "Night Nail",
    tag: "HOT TREND",
    description:
      "Mẫu nail premium design mang đến vẻ ngoài tôn da, tinh tế phù hợp với nhiều phong cách khác nhau.",
    features: ["Tôn da", "Đơn giản", "Tinh tế", "Thạch"],
    careTip: "Sử dụng găng tay khi làm việc nhà để bảo vệ màu sơn.",
    nailStyle: "Sơn thạch trong veo",
    length: "Cực dài",
    shape: "Nhọn",
    suitability: "Cô dâu trong ngày cưới",
  },
  {
    img: "/images/process/29.png",
    title: "Premium Design",
    price: "Night Nail",
    tag: "BASIC",
    description:
      "Mẫu nail premium design mang đến vẻ ngoài sang trọng, nổi bật phù hợp với nhiều phong cách khác nhau.",
    features: ["Sang trọng", "Đính đá", "Nổi bật", "Tiệc tùng"],
    careTip: "Tránh dùng móng cạy các vật cứng để không làm mẻ gel.",
    nailStyle: "Mắt mèo kim cương",
    length: "Ngắn",
    shape: "Thang",
    suitability: "Đi học, đi làm",
  },
  {
    img: "/images/process/30.png",
    title: "Premium Design",
    price: "Night Nail",
    tag: "BEST SELLER",
    description:
      "Mẫu nail premium design mang đến vẻ ngoài cá tính, độc đáo phù hợp với nhiều phong cách khác nhau.",
    features: ["Cá tính", "Tráng gương", "Độc đáo", "Hiện đại"],
    careTip: "Thoa dầu dưỡng móng mỗi tối trước khi đi ngủ.",
    nailStyle: "Tráng gương sang trọng",
    length: "Vừa",
    shape: "Hạnh nhân",
    suitability: "Dự tiệc, sự kiện",
  },
  {
    img: "/images/process/31.png",
    title: "Premium Design",
    price: "Night Nail",
    tag: "HOT TREND",
    description:
      "Mẫu nail premium design mang đến vẻ ngoài trắng sữa, thanh lịch phù hợp với nhiều phong cách khác nhau.",
    features: ["Trắng sữa", "Nhũ ngọc trai", "Thanh lịch", "Nhẹ nhàng"],
    careTip:
      "Dưỡng ẩm vùng da quanh móng thường xuyên để bộ nail luôn bền đẹp.",
    nailStyle: "Đính đá lấp lánh",
    length: "Dài",
    shape: "Oval",
    suitability: "Hẹn hò, dạo phố",
  },
  {
    img: "/images/process/32.png",
    title: "Premium Design",
    price: "Night Nail",
    tag: "NEW",
    description:
      "Mẫu nail premium design mang đến vẻ ngoài quyến rũ, mắt mèo phù hợp với nhiều phong cách khác nhau.",
    features: ["Quyến rũ", "Huyền bí", "Mắt mèo", "Lấp lánh"],
    careTip: "Hạn chế tiếp xúc trực tiếp với hóa chất tẩy rửa mạnh.",
    nailStyle: "Vẽ vân đá hoa cương",
    length: "Cực dài",
    shape: "Vuông",
    suitability: "Cô dâu trong ngày cưới",
  },
  {
    img: "/images/process/33.png",
    title: "Premium Design",
    price: "Night Nail",
    tag: "BEST SELLER",
    description:
      "Mẫu nail premium design mang đến vẻ ngoài tôn da, tinh tế phù hợp với nhiều phong cách khác nhau.",
    features: ["Tôn da", "Đơn giản", "Tinh tế", "Thạch"],
    careTip: "Sử dụng găng tay khi làm việc nhà để bảo vệ màu sơn.",
    nailStyle: "Ombre - Nhũ ngọc trai",
    length: "Ngắn",
    shape: "Nhọn",
    suitability: "Đi học, đi làm",
  },
  {
    img: "/images/process/34.png",
    title: "Premium Design",
    price: "Night Nail",
    tag: "BASIC",
    description:
      "Mẫu nail premium design mang đến vẻ ngoài sang trọng, nổi bật phù hợp với nhiều phong cách khác nhau.",
    features: ["Sang trọng", "Đính đá", "Nổi bật", "Tiệc tùng"],
    careTip: "Tránh dùng móng cạy các vật cứng để không làm mẻ gel.",
    nailStyle: "Sơn thạch trong veo",
    length: "Vừa",
    shape: "Thang",
    suitability: "Dự tiệc, sự kiện",
  },
  {
    img: "/images/process/35.png",
    title: "Premium Design",
    price: "Night Nail",
    tag: "HOT TREND",
    description:
      "Mẫu nail premium design mang đến vẻ ngoài cá tính, độc đáo phù hợp với nhiều phong cách khác nhau.",
    features: ["Cá tính", "Tráng gương", "Độc đáo", "Hiện đại"],
    careTip: "Thoa dầu dưỡng móng mỗi tối trước khi đi ngủ.",
    nailStyle: "Mắt mèo kim cương",
    length: "Dài",
    shape: "Hạnh nhân",
    suitability: "Hẹn hò, dạo phố",
  },
  {
    img: "/images/process/36.png",
    title: "Premium Design",
    price: "Night Nail",
    tag: "NEW",
    description:
      "Mẫu nail premium design mang đến vẻ ngoài trắng sữa, thanh lịch phù hợp với nhiều phong cách khác nhau.",
    features: ["Trắng sữa", "Nhũ ngọc trai", "Thanh lịch", "Nhẹ nhàng"],
    careTip:
      "Dưỡng ẩm vùng da quanh móng thường xuyên để bộ nail luôn bền đẹp.",
    nailStyle: "Tráng gương sang trọng",
    length: "Cực dài",
    shape: "Oval",
    suitability: "Cô dâu trong ngày cưới",
  },
  {
    img: "/images/process/37.png",
    title: "Premium Design",
    price: "Night Nail",
    tag: "BEST SELLER",
    description:
      "Mẫu nail premium design mang đến vẻ ngoài quyến rũ, mắt mèo phù hợp với nhiều phong cách khác nhau.",
    features: ["Quyến rũ", "Huyền bí", "Mắt mèo", "Lấp lánh"],
    careTip: "Hạn chế tiếp xúc trực tiếp với hóa chất tẩy rửa mạnh.",
    nailStyle: "Đính đá lấp lánh",
    length: "Ngắn",
    shape: "Vuông",
    suitability: "Đi học, đi làm",
  },
];
